### ISSUE TITLE
引入 g2-mobile 对象为空，g2却无此问题，请确认

### ISSUE THREAD

**Issue by shufangjian** [antvis/g2-mobile#1]
g2-mobile 版本 2.0.0

[https://segmentfault.com/q/1010000006891658](url)

**Comment by TomHuangCN** [comment]
什么方式引入的？<script>标签？

**Comment by shufangjian** [comment]
VUE 框架
var GM = require('g2-mobile');
console.log(GM);

同样的方式引入g2 可以打印出对象

var G2 = require('g2');
console.log(G2);

看了下代码 是不是g2-mobile 没有做 module 处理

**Comment by TomHuangCN** [comment]
是我们的问题，下个小版本解决
