### ISSUE TITLE
在chrome-61.0.3163.79中，带动画的图表显示异常

### ISSUE THREAD

**Issue by mkgsac** [antvis/g2-mobile#12]
今天更新chrome到版本61.0.3163.79以后，带动画的图表显示不出来了。官网的示例也是显示不出来了

**Comment by dxq613** [comment]
我也升级到了 最新版本，没有发现问题：

版本 61.0.3163.79（正式版本） （64 位）

**Comment by mkgsac** [comment]
奇怪，我现在打开官网的这个示例，只显示了网格线和一个点，曲线不显示
[带平铺动画的多类型线图](https://antv.alipay.com/g2-mobile/demo/02-line/line-dash.html)

**Comment by dxq613** [comment]
我这边是正常的。动画是使用了 canvas 填充图片的方式实现的，这种重要的api 不可能出现问题啊。看看是否有js 报错。

**Comment by mkgsac** [comment]
![img](https://user-images.githubusercontent.com/11793470/30624267-0396b6ca-9def-11e7-9552-9e8c7261fc34.png)

**Comment by mkgsac** [comment]
这个问题在chrome 62.0.3202.94里修复了
