### ISSUE TITLE
创建Chart不支持container属性

### ISSUE THREAD

**Issue by mkgsac** [antvis/g2-mobile#2]
g2-mobile 只能用 **id** 值来指定图表容器，不支持通过 **container** 直接传入容器的 html 节点对象

**Comment by dxq613** [comment]
基本的原则是：简化图表的初始化逻辑，控制代码量

**Comment by ch-daisy** [comment]
已经支持了，详情：https://antv.alipay.com/g2-mobile/api/index.html#el
