### ISSUE TITLE
g2-mobile 拆线图，线的自定义颜色问题

### ISSUE THREAD

**Issue by arronf2e** [antvis/g2-mobile#4]
我看到文档中有一个colorCallback，可以让用户自定义颜色，请问怎么让线条支持几种颜色渐变呢

**Comment by ch-daisy** [comment]
可以使用canvas原生的渐变色方法createLinearGradient，具体使用可以参考这个示例：https://antv.alipay.com/g2-mobile/demo/02-line/line-html.html

**Comment by arronf2e** [comment]
@ch-daisy  OK，我试下
