### ISSUE TITLE
请问g2-mobile目前是否属于开源项目，有开源协议么？ 可否在商业项目中使用？

### ISSUE THREAD

**Issue by zeroven** [antvis/g2-mobile#6]
如题：请问g2-mobile目前是否属于开源项目，有开源协议么？ 可否在商业项目中使用？
同样g2的Web PC版呢

**Comment by dxq613** [comment]
可以在商业中应用，协议目前是gpl协议，6月份会开源，开放所有代码。

**Comment by zeroven** [comment]
好的，thks 我们项目大约在五六月份上线，期待g2越来越多的star
