### ISSUE TITLE
请问，g2-mobile可以提供非压缩的源码么？

### ISSUE THREAD

**Issue by rockywu** [antvis/g2-mobile#8]
是这样的由于业务需求，只需要部分图标绘制主题，而整个包体量太大，希望有源码可以自由压缩。

**Comment by dxq613** [comment]
你想控制到多大，g2-mobile确实加入了不少额外的块，包括k线图、area、guide、animate功能都是单独的包，只是如果缺了这些功能，易用性、完整性都不太好。我们其实在支付宝钱包、淘宝的一些客户端上都使用了g2-mobile，这个大小其实还能接受

**Comment by dxq613** [comment]
移动端对性能、扩展性、多样性的要求非常严格，基本上现成的demo没有一个能直接使用，都会自己定制图形、使用大量的guide，自己监听事件使用g2-mobile的接口进行交互。
